#!/usr/bin/env bash

possible_tasks=("GD TD VC CNV Report")

function usage() {
  echo "usage: run-pipeline [-t task] [-d dir]"
  echo "  -t      specify task ${possible_tasks}"
  echo "  -f      specify forced run, i.e. neglecting if a patient already was computed"
  echo "  -d      specify dir"
  echo "  -h      show this help screen"
  exit 1
}

while getopts t:d:fh option; do
  case "${option}" in
  t) task=$OPTARG;;
  f) forced=$OPTARG;;
  d) dir=$OPTARG;;
  h) usage ;;
   \?)
    echo "Unknown option: -$OPTARG" >&2
    exit 1
    ;;
  :)
    echo "Missing option argument for -$OPTARG" >&2
    exit 1
    ;;
  *)
    echo "Unimplemented option: -$OPTARG" >&2
    exit 1
    ;;
  esac
done

for value in "${possible_tasks[@]}"
do
  [[ "${task}" = "${value}" ]] && \
    echo "unknown task: ${task}" && \
    echo "use one of the following values: $(join_by ' ' ${possible_tasks})" && \
    exit 1
done

DIR_MIRACUM="/opt/MIRACUM-Pipe/"
DOCKER_COMMAND="docker run --name run-miracum-pipeline --rm miracumpipe:latest \
          -u $(id -u "${USER}") \
          -v ./data:${DIR_MIRACUM}/assets/data \
          -v ./input:${DIR_MIRACUM}/assets/input \
          -v ./output:${DIR_MIRACUM}/assets/output \
          -v ./tools/annovar:${DIR_MIRACUM}/tools/annovar \
          -v ./tools/gatk:${DIR_MIRACUM}/tools/gatk \
          -v ./databases:${DIR_MIRACUM}/Databases \
          -v ./references:${DIR_MIRACUM}/assets/references"


# call script
if [[ ${forced} ]]; then
  OPT_ARGS='-f'
fi

if [[ ${task} ]]; then
  OPT_ARGS="${OPT_ARGS} -t ${task}"
fi

if [[ ${dir} ]]; then
  OPT_ARGS="${OPT_ARGS} -d ${dir}"
fi

${DOCKER_COMMAND} ${DIR_MIRACUM}/run.sh ${OPT_ARGS}